#!/usr/bin/env python3
"""Render docs/19-pyfa-feature-inventory.yaml into the tables of docs/19-pyfa-feature-inventory.md
(between the GENERATED markers) and into docs/19-pyfa-feature-inventory.csv."""
import csv, collections, pathlib, yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
Y = ROOT / "docs/19-pyfa-feature-inventory.yaml"
MD = ROOT / "docs/19-pyfa-feature-inventory.md"
CSV = ROOT / "docs/19-pyfa-feature-inventory.csv"
COLS = ["f", "mcp", "web"]
AREAS = [("ENG-CORE", "Engine core"), ("ENG-MOD", "Modules"), ("ENG-SHIP", "Ships, modes, subsystems, structures"),
         ("ENG-DRN", "Drones"), ("ENG-FTR", "Fighters"), ("ENG-IMP", "Implants and boosters"),
         ("ENG-CAP", "Capacitor"), ("ENG-DEF", "Defense / tank"), ("ENG-OFF", "Offense / mining"),
         ("ENG-NAV", "Navigation"), ("ENG-TGT", "Targeting / sensors / misc"), ("ENG-PROJ", "Projection / remote effects"),
         ("ENG-FLT", "Fleet / command"), ("ENG-ENV", "Environment"), ("ENG-VAL", "Validation / restrictions"),
         ("GRF", "Graphs"), ("CHR", "Characters and skills"), ("PRC", "Prices"), ("FMT", "Import / export"),
         ("ESI", "ESI / SSO"), ("DB", "Persistence / fit library"), ("PRF", "Damage patterns / target profiles"),
         ("MKT", "Market / item info"), ("UI", "GUI panes, columns, menus, preferences"), ("SVC", "Services / misc")]
SYM = {"have": "✅ have", "partial": "🟡 partial", "missing": "❌ missing", "n/a": "– n/a"}


def area(i):
    return next(p for p, _ in sorted(AREAS, key=lambda a: -len(a[0])) if i["id"].startswith(p + "-"))


def esc(s):
    return str(s).replace("|", "\\|").replace("\n", " ")


def main():
    doc = yaml.safe_load(Y.read_text())
    items = doc["items"]
    cnt = {c: collections.Counter(i[c] for i in items) for c in COLS}
    out = ["<!-- GENERATED by tools/render_inventory.py from the YAML; do not edit by hand -->", "",
           f"## Counts ({len(items)} items)", "",
           "| column | have | partial | missing | n/a |", "|---|---|---|---|---|"]
    for c, lab in zip(COLS, ["F engine/CLI/WASM", "eve-fit-mcp", "eve-fit-web"]):
        out.append(f"| {lab} | {cnt[c]['have']} | {cnt[c]['partial']} | {cnt[c]['missing']} | {cnt[c]['n/a']} |")
    out += ["", "Per area (have/partial/missing, n/a not counted):", "", "| area | items | F | MCP | WEB |", "|---|---|---|---|---|"]
    by = collections.defaultdict(list)
    for i in items:
        by[area(i)].append(i)
    for p, name in AREAS:
        g = by.get(p, [])
        if not g:
            continue
        f = lambda c: "/".join(str(sum(1 for i in g if i[c] == s)) for s in ("have", "partial", "missing"))
        out.append(f"| {p} {name} | {len(g)} | {f('f')} | {f('mcp')} | {f('web')} |")
    out += ["", "## Items", ""]
    for p, name in AREAS:
        g = by.get(p, [])
        if not g:
            continue
        out += [f"### {p}: {name}", "", "| id | feature | Pyfa source | F | MCP | WEB |", "|---|---|---|---|---|---|"]
        for i in g:
            out.append(f"| {i['id']} | **{esc(i['name'])}**: {esc(i['description'])} | `{esc(i['pyfa_src'])}` | "
                       + " | ".join(f"{SYM[i[c]]}: {esc(i[c + '_evidence'])}" for c in COLS) + " |")
        out.append("")
    md = MD.read_text()
    a, b = "<!-- BEGIN GENERATED -->", "<!-- END GENERATED -->"
    head, rest = md.split(a, 1)
    tail = rest.split(b, 1)[1]
    MD.write_text(head + a + "\n" + "\n".join(out) + "\n" + b + tail)
    with CSV.open("w", newline="") as fh:
        w = csv.writer(fh)
        keys = ["id", "area", "name", "description", "pyfa_src"] + [k for c in COLS for k in (c, c + "_evidence")]
        w.writerow(keys)
        for i in items:
            w.writerow([i["id"], area(i)] + [i[k] for k in keys[2:]])
    print({c: dict(cnt[c]) for c in COLS})


if __name__ == "__main__":
    main()
